#pragma once

namespace WorldGenerator
{
	struct __declspec(dllexport) RoomLayoutConfig
	{
		// For BSP 
		const static int minRoom2DSize = 4;
		const static int maxRoom2DSize = 12;
		const static int roomHeight = 3;
		const static int verticalRoomLinkLength = 5;
		const static int verticalRoomLinkWidth = 2;

		Vector3 mapSize; // z is floor count
		float roomDensity; // density such that room count = floor(Rooms generated by BSP * roomDensity)
		float pathLengthCoeff; // coeff such that length of start-end path <= floor(room count * pathLengthCoeff)
		float edgeDensityCoeff; // coeff that defines edge density in graph
	};
}