#pragma once
namespace WorldGenerator
{
	struct RoomLayoutConfig
	{
		// For BSP 
		const static int minRoom2DSize = 4;
		const static int maxRoom2DSize = 12;
		const static int roomHeight = 3;
		const static int verticalRoomLinkLength = 2;
		const static int verticalRoomLinkWidth = 1;

		Vector3 mapSize;
		float roomDensity; // density such that room count = floor(Rooms generated by BSP * roomDensity)
		float pathLengthCoeff; // coeff such that length of start-end path <= floor(room count * pathLengthCoeff)
		float edgeDensityCoeff; // coeff that defines edge density in graph
	};
}