#pragma once
namespace WorldGenerator
{
	struct RoomLayoutConfig
	{
		// For BSP 
		const static int minRoom2DSize = 4;
		const static int maxRoom2DSize = 12;
		const static int minRoomHeight = 4;
		const static int maxRoomHeight = 8;

		Vector3 mapSize;
		float roomDensity; // density such that room count = floor(Rooms generated by BSP * roomDensity)
		float pathLengthCoeff; // coeff such that length of start-end path <= floor(room count * pathLengthCoeff)
		float edgeDensityCoeff; // coeff that defines edge density in graph
	};
}